#!/bin/sh

option=$(printf '%s\n%s\n%s' \
	'shutdown' \
	'reboot' \
	'suspend' \
	| dmenu)

case $option in
	'shutdown') systemctl poweroff;;
	'reboot') systemctl reboot;;
	'suspend') systemctl suspend;;
esac
